- id: asimov-lets-get-together-medium-1
  title: Let's Get Together
  author: Isaac Asimov
  source: "Project Gutenberg ebook #68377"
  source_url: https://www.gutenberg.org/ebooks/68377
  text: >
    A kind of peace had endured for a century and people had forgotten what
    anything else was like. They would scarcely have known how to react had they
    discovered that a kind of war had finally come. Elias Lynn, Chief of the
    Bureau of Robotics, was not sure how he ought to react when he finally found
    out. The Bureau was headquartered in Cheyenne, in line with the century old
    trend toward decentralization, and Lynn stared dubiously at the young
    Security officer from Washington who had brought the news.
- id: asimov-lets-get-together-medium-2
  title: Let's Get Together
  author: Isaac Asimov
  source: "Project Gutenberg ebook #68377"
  source_url: https://www.gutenberg.org/ebooks/68377
  text: >
    It came to him quietly. Lynn found he had nothing to do but sit in his office
    alone, with an executive position that had grown merely titular. Perhaps that
    helped. It gave him time to think, to picture the creative scientists of half
    the world converging on Cheyenne. It was Breckenridge who, with cool
    efficiency, was handling the details of preparation. There had been a kind of
    confidence in the way he said that they should get together and they would
    win. It came to Lynn so quietly that anyone watching him might have seen only
    his eyes blink slowly twice.
- id: capek-rur-medium-1
  title: R.U.R.
  author: Karel Čapek
  source: "Project Gutenberg ebook #59112"
  source_url: https://www.gutenberg.org/ebooks/59112
  text: >
    Young Rossum invented a worker with the minimum amount of requirements. He
    had to simplify him. He rejected everything that did not contribute directly
    to the progress of work. Everything that makes man more expensive. In fact he
    rejected man and made the Robot. My dear Miss Glory, the Robots are not
    people. Mechanically they are more perfect than we are; they have an
    enormously developed intelligence, but they have no soul. Helena asked how he
    knew they had no soul, and Domin asked whether she had ever seen what a Robot
    looked like inside.
