- id: asimov-silly-asses-slow-1
  title: Silly Asses
  author: Isaac Asimov
  source: "Project Gutenberg ebook #78751"
  source_url: https://www.gutenberg.org/ebooks/78751
  text: >
    Naron of the long-lived Rigellian race was the fourth of his line to keep the
    Galactic records. He had the large book which contained the list of the
    numerous races throughout the Galaxies that had developed intelligence, and
    the much smaller book listing those races that had reached maturity and had
    qualified for the Galactic Federation. In the first book, a number of those
    listed were crossed out; those that, for one reason or another, had failed.
    Misfortune and social maladjustment took their toll. In the smaller book,
    however, no member listed had yet blanked out.
- id: asimov-youth-slow-1
  title: Youth
  author: Isaac Asimov
  source: "Project Gutenberg ebook #31547"
  source_url: https://www.gutenberg.org/ebooks/31547
  text: >
    The Industrialist tried. He grimaced with the effort of it, thinking over and
    over again that the youngsters were ignorant of his identity. And the thought
    was suddenly in his mind. They were quite aware of it, and because they knew
    the boys meant well by them according to their own view of the matter, they
    did not attempt to attack them. The Industrialist wondered aloud about attack,
    and the answering thought came quietly. They were armed. One of the little
    creatures in the cage lifted a metal object, and there was a sudden hole in
    the top of the cage.
- id: forster-machine-stops-slow-1
  title: The Machine Stops
  author: E. M. Forster
  source: "Project Gutenberg ebook #72890"
  source_url: https://www.gutenberg.org/ebooks/72890
  text: >
    Imagine, if you can, a small room, hexagonal in shape, like the cell of a
    bee. It is lighted neither by window nor by lamp, yet it is filled with a
    soft radiance. There are no apertures for ventilation, yet the air is fresh.
    There are no musical instruments, and yet, at the moment that my meditation
    opens, this room is throbbing with melodious sounds. An arm chair is in the
    centre, by its side a reading desk. That is all the furniture. And in the arm
    chair there sits a woman with a face as white as a fungus.
